package tests.Wallet.M_Pesa;

import com.aventstack.extentreports.ExtentTest;
import com.aventstack.extentreports.MediaEntityBuilder;
import framework.entity.User;
import framework.features.ApiManagement;
import framework.features.CartManagement;
import framework.features.Login;
import framework.pageObjects.Wallet.PaymentInfo.WalletPaymentInfo_pg;
import framework.util.reportManagement.ScreenShot;
import org.testng.annotations.Test;
import tests.TestInit;

/**
 * Created by karthik.m on 6/18/2018.
 */
public class ToVerifyAutoGeneratedRefIDIsDisplayed extends TestInit
{
    @Test
    public void toVerifyAutoGeneratedRefID() throws Exception {
        ExtentTest t1 = pNode.createNode("PAYPLUS-673-Consumer-04", "To Verify Auto-Generated Reference-ID Is Displayed");
        User newUser = new User();

        Login.init(t1)
                .validLogin();

        CartManagement.init(t1)
                .addDefaultItemToCart();

        WalletPaymentInfo_pg.init(t1)
                .clickOnWallet()
                .clickOnMpesaRadiobtn()
                .clickOnPayNowBtn()
                .enterMobNumMP(newUser.msisdn)
                .clickOnGenerateID();

        String refNum = WalletPaymentInfo_pg.init(t1)
                .getReferenceNum();

        boolean refNumDisplay = WalletPaymentInfo_pg.init(t1)
                .verifyRefNum();
        if(refNumDisplay == true)
        {
            t1.pass("Reference ID Is Displayed & ID is "+ refNum);
            t1.pass("", MediaEntityBuilder.createScreenCaptureFromPath(ScreenShot.TakeScreenshot()).build());

        }
        else {
            t1.fail("Reference ID Is Not Displayed");
            t1.fail("", MediaEntityBuilder.createScreenCaptureFromPath(ScreenShot.TakeScreenshot()).build());

        }
    }

    }
